###
GET http://localhost:3000/api/doctor
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMjA1NjBjZjNmM2FmYmRlMGYyMTA1OSIsImlhdCI6MTYxMjgyODg1NCwiZXhwIjoxNjEyOTE1MjU0fQ.RR6oyzMzZsZS6AokqRIbd_TwSBL9MTqCUG7xsy5xuCk

###
POST http://localhost:3000/api/doctor
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMjAzNjcwMmMzOGU5ZWQyYzAwM2M0MSIsImlhdCI6MTYxMjkwODk5MywiZXhwIjoxNjEyOTk1MzkzfQ.TJhRZnimFeps2WxVQBtlxN9nKuahTy5aFhyfao8TvB8
Content-Type: application/json

{
    "name": "Carlos Mendez",
    "hospitalId": "6020bb0312ca220c29f1215b"
}

###
PUT http://localhost:3000/api/doctor/6020be383a728691d4d73bbc
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMjA1NjBjZjNmM2FmYmRlMGYyMTA1OSIsImlhdCI6MTYxMjgyODg1NCwiZXhwIjoxNjEyOTE1MjU0fQ.RR6oyzMzZsZS6AokqRIbd_TwSBL9MTqCUG7xsy5xuCk
Content-Type: application/json

{
    "name": "Gilberto Santa Rosa",
    "hospitalId": "6020bb1b12ca220c29f1215c"
}

###
DELETE http://localhost:3000/api/doctor/6020c30407d772fea8514156
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMjA1NjBjZjNmM2FmYmRlMGYyMTA1OSIsImlhdCI6MTYxMjgyODg1NCwiZXhwIjoxNjEyOTE1MjU0fQ.RR6oyzMzZsZS6AokqRIbd_TwSBL9MTqCUG7xsy5xuCk
